In [1]:
ls

__pycache__/             first-week.ipynb         sixth-weeks.ipynb
array_archive.npz        fourth-weeks.ipynb       some_array.npy
array_archove.npz        ipython_script_test.py   some_module.py
examples/                ipython_script_test2.py  third-week.ipynb
fifth-weeks.ipynb        second-week.ipynb

In [2]:
cd examples/

/Users/jo-eun-yeob/Workspace/TIL/Data-analysis/examples

In [3]:
ls

array_ex.txt                macrodata.csv
csv_mindex.csv              out.csv
ex1.csv                     segismundo.txt
ex1.xlsx                    spx.csv
ex2.csv                     stinkbug.png
ex3.csv                     stock_px.csv
ex3.txt                     stock_px_2.csv
ex4.csv                     test_file.csv
ex5.csv                     tips.csv
ex6.csv                     tseries.csv
ex7.csv                     volume.csv
example.json                yahoo_price.pkl
fdic_failed_bank_list.html  yahoo_volume.pkl
ipython_bug.py

In [4]:
pwd

'/Users/jo-eun-yeob/Workspace/TIL/Data-analysis/examples'

In [5]:
!cat examples/ex1.csv

cat: examples/ex1.csv: No such file or directory

In [6]:
ls

array_ex.txt                macrodata.csv
csv_mindex.csv              out.csv
ex1.csv                     segismundo.txt
ex1.xlsx                    spx.csv
ex2.csv                     stinkbug.png
ex3.csv                     stock_px.csv
ex3.txt                     stock_px_2.csv
ex4.csv                     test_file.csv
ex5.csv                     tips.csv
ex6.csv                     tseries.csv
ex7.csv                     volume.csv
example.json                yahoo_price.pkl
fdic_failed_bank_list.html  yahoo_volume.pkl
ipython_bug.py

In [8]:
cat ex1.csv

a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [9]:
import pandas as pd
import numpy as np
df = pd.read_csv('ex1.csv')
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [10]:
pd.read_table('ex1.csv', sep=',')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [11]:
cat ex2.csv

1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [18]:
pd.read_csv('ex2.csv', header=None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [19]:
pd.read_csv('ex2.csv', names=['a','b','c','d','message'])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [20]:
cat csv_mindex.csv

key1,key2,value1,value2
one,a,1,2
one,b,3,4
one,c,5,6
one,d,7,8
two,a,9,10
two,b,11,12
two,c,13,14
two,d,15,16

In [21]:
parsed = pd.read_csv('csv_mindex.csv', index_col = ['key1', 'key2'])
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [22]:
list(open('ex3.txt'))

['            A         B         C\n',
 'aaa -0.264438 -1.026059 -0.619500\n',
 'bbb  0.927272  0.302904 -0.032399\n',
 'ccc -0.264273 -0.386314 -0.217601\n',
 'ddd -0.871858 -0.348382  1.100491\n']

In [27]:
result = pd.read_csv('ex3.txt', sep='\s+')
result

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [28]:
cat ex4.csv

# hey!
a,b,c,d,message
# just wanted to make things more difficult for you
# who reads CSV files with computers, anyway?
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [29]:
pd.read_csv('ex4.csv', skiprows=[0,2,3])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [30]:
cat ex5.csv

something,a,b,c,d,message
one,1,2,3,4,NA
two,5,6,,8,world
three,9,10,11,12,foo

In [31]:
result = pd.read_csv('ex5.csv')
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [32]:
result = pd.read_csv('ex5.csv', na_values=['NULL'])
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [33]:
sentinels = {'message':['foo', 'world'], 'something':['two']}
pd.read_csv('ex5.csv', na_values=sentinels)

  something  a   b     c   d  message
0       one  1   2   3.0   4      NaN
1       NaN  5   6   NaN   8      NaN
2     three  9  10  11.0  12      NaN

In [41]:
pd.options.display.max_rows = 20

In [42]:
result = pd.read_csv('ex6.csv')
result

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [44]:
pd.read_csv('ex6.csv', nrows=5) # nrows 숫자만큼만 읽어옴

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [45]:
pd.read_csv('ex6.csv').head() # 다 읽어오고나서 5개만

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [46]:
data = pd.read_csv('ex5.csv')
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [47]:
data.to_csv('out.csv')

In [48]:
cat out.csv

,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo

In [49]:
cat ex5.csv

something,a,b,c,d,message
one,1,2,3,4,NA
two,5,6,,8,world
three,9,10,11,12,foo

In [51]:
import sys
data.to_csv(sys.stdout, sep='|')

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo

In [54]:
data.to_csv(sys.stdout, na_rep="test")

,something,a,b,c,d,message
0,one,1,2,3.0,4,test
1,two,5,6,test,8,world
2,three,9,10,11.0,12,foo

In [55]:
data.to_csv(sys.stdout, index=False, header=False)

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo

In [57]:
data.to_csv(sys.stdout, index=False, columns=['b', 'a', 'c'])

b,a,c
2,1,3.0
6,5,
10,9,11.0

In [58]:
ts = pd.Series(np.arange(7), index=np.arange(7))
ts

0    0
1    1
2    2
3    3
4    4
5    5
6    6
dtype: int64

In [60]:
ts.to_csv('tseries.csv')

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  """Entry point for launching an IPython kernel.

In [61]:
cat tseries.csv

0,0
1,1
2,2
3,3
4,4
5,5
6,6

In [62]:
cat ex7.csv

"a","b","c"
"1","2","3"
"1","2","3"

In [63]:
import csv
f = open('ex7.csv')
reader = csv.reader(f)

for line in reader:
    print(line)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

In [67]:
obj = """
{"name":"Wes",
 "places_lived" : ["United states", "Spain", "Germany"],
 "pet" : null,
 "siblings":[{"name": "scott", "age": 30, "pets":["zeus", "zuko"]},
             {"name": "katie", "age":38,
              "pets":["sixes", "stache", "cisco"]}]
}
"""

In [70]:
import json
result = json.loads(obj)
result

{'name': 'Wes',
 'places_lived': ['United states', 'Spain', 'Germany'],
 'pet': None,
 'siblings': [{'name': 'scott', 'age': 30, 'pets': ['zeus', 'zuko']},
  {'name': 'katie', 'age': 38, 'pets': ['sixes', 'stache', 'cisco']}]}

In [71]:
asjson = json.dumps(result)
type(asjson)

str

In [72]:
asjson

'{"name": "Wes", "places_lived": ["United states", "Spain", "Germany"], "pet": null, "siblings": [{"name": "scott", "age": 30, "pets": ["zeus", "zuko"]}, {"name": "katie", "age": 38, "pets": ["sixes", "stache", "cisco"]}]}'

In [73]:
siblings = pd.DataFrame(result['siblings'], columns=['name', 'age'])
siblings

    name  age
0  scott   30
1  katie   38

In [74]:
cat example.json

[{"a": 1, "b": 2, "c": 3},
 {"a": 4, "b": 5, "c": 6},
 {"a": 7, "b": 8, "c": 9}]

In [75]:
data = pd.read_json('example.json')
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [77]:
print(data.to_json())

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}

In [78]:
print(data.to_json(orient='records'))

[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]

In [79]:
tables = pd.read_html('fdic_failed_bank_list.html')
tables

[                             Bank Name             City  ST   CERT  \
 0                          Allied Bank         Mulberry  AR     91
 1         The Woodbury Banking Company         Woodbury  GA  11297
 2               First CornerStone Bank  King of Prussia  PA  35312
 3                   Trust Company Bank          Memphis  TN   9956
 4           North Milwaukee State Bank        Milwaukee  WI  20364
 ..                                 ...              ...  ..    ...
 542                 Superior Bank, FSB         Hinsdale  IL  32646
 543                Malta National Bank            Malta  OH   6629
 544    First Alliance Bank & Trust Co.       Manchester  NH  34264
 545  National State Bank of Metropolis       Metropolis  IL   3815
 546                   Bank of Honolulu         Honolulu  HI  21029

                    Acquiring Institution        Closing Date  \
 0                           Today's Bank  September 23, 2016
 1                            United Bank     August 19, 2016
 2    First-Citizens Bank & Trust Company         May 6, 2016
 3             The Bank of Fayette County      April 29, 2016
 4    First-Citizens Bank & Trust Company      March 11, 2016
 ..                                   ...                 ...
 542                Superior Federal, FSB       July 27, 2001
 543                    North Valley Bank         May 3, 2001
 544  Southern New Hampshire Bank & Trust    February 2, 2001
 545              Banterra Bank of Marion   December 14, 2000
 546                   Bank of the Orient    October 13, 2000

           Updated Date
 0    November 17, 2016
 1    November 17, 2016
 2    September 6, 2016
 3    September 6, 2016
 4        June 16, 2016
 ..                 ...
 542    August 19, 2014
 543  November 18, 2002
 544  February 18, 2003
 545     March 17, 2005
 546     March 17, 2005

 [547 rows x 7 columns]]

In [80]:
failuers = tables[0]
failuers

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016"
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016"
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016"
5,Hometown National Bank,Longview,WA,35156,Twin City Bank,"October 2, 2015","April 13, 2016"
6,The Bank of Georgia,Peachtree City,GA,35259,Fidelity Bank,"October 2, 2015","October 24, 2016"
7,Premier Bank,Denver,CO,34112,"United Fidelity Bank, fsb","July 10, 2015","August 17, 2016"
8,Edgebrook Bank,Chicago,IL,57772,Republic Bank of Chicago,"May 8, 2015","July 12, 2016"
9,Doral Bank En Espanol,San Juan,PR,32102,Banco Popular de Puerto Rico,"February 27, 2015","May 13, 2015"
...,...,...,...,...,...,...,...
537,"NextBank, NA",Phoenix,AZ,22314,No Acquirer,"February 7, 2002","February 5, 2015"
538,Oakwood Deposit Bank Co.,Oakwood,OH,8966,The State Bank & Trust Company,"February 1, 2002","October 25, 2012"
539,Bank of Sierra Blanca,Sierra Blanca,TX,22002,The Security State Bank of Pecos,"January 18, 2002","November 6, 2003"
540,"Hamilton Bank, NA En Espanol",Miami,FL,24382,Israel Discount Bank of New York,"January 11, 2002","September 21, 2015"
541,Sinclair National Bank,Gravette,AR,34248,Delta Trust & Bank,"September 7, 2001","February 10, 2004"
542,"Superior Bank, FSB",Hinsdale,IL,32646,"Superior Federal, FSB","July 27, 2001","August 19, 2014"
543,Malta National Bank,Malta,OH,6629,North Valley Bank,"May 3, 2001","November 18, 2002"
544,First Alliance Bank & Trust Co.,Manchester,NH,34264,Southern New Hampshire Bank & Trust,"February 2, 2001","February 18, 2003"
545,National State Bank of Metropolis,Metropolis,IL,3815,Banterra Bank of Marion,"December 14, 2000","March 17, 2005"
546,Bank of Honolulu,Honolulu,HI,21029,Bank of the Orient,"October 13, 2000","March 17, 2005"

In [82]:
close_timestamps = pd.to_datetime(failuers['Closing Date'])
close_timestamps

0     2016-09-23
1     2016-08-19
2     2016-05-06
3     2016-04-29
4     2016-03-11
         ...
542   2001-07-27
543   2001-05-03
544   2001-02-02
545   2000-12-14
546   2000-10-13
Name: Closing Date, Length: 547, dtype: datetime64[ns]

In [83]:
close_timestamps.dt.year.value_counts()

2010    157
2009    140
2011     92
2012     51
2008     25
2013     24
2014     18
2002     11
2015      8
2016      5
2004      4
2001      4
2007      3
2003      3
2000      2
Name: Closing Date, dtype: int64

In [84]:
frame = pd.read_csv('ex1.csv')
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [85]:
frame.to_pickle('frame-pickle')
pd.read_pickle('frame-pickle')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [93]:
pip install --upgrade pip

Collecting pip
  Downloading https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl (1.4MB)
     |████████████████████████████████| 1.4MB 392kB/s eta 0:00:01
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-19.3.1
Note: you may need to restart the kernel to use updated packages.

In [91]:
frame = pd.DataFrame({'a': np.random.randn(100)})
store = pd.HDFStore('mydata.h5')
store['obj1'] = frame
store['obj1_col'] = frame['a']
store

<class 'pandas.io.pytables.HDFStore'>
File path: mydata.h5

In [94]:
store['obj1']

           a
0  -0.648454
1   1.506657
2   0.196938
3   0.435900
4  -0.651262
..       ...
95 -2.438003
96 -0.033026
97 -0.273475
98 -1.348726
99  0.113490

[100 rows x 1 columns]

In [95]:
store['obj1_col']

0    -0.648454
1     1.506657
2     0.196938
3     0.435900
4    -0.651262
        ...
95   -2.438003
96   -0.033026
97   -0.273475
98   -1.348726
99    0.113490
Name: a, Length: 100, dtype: float64

In [96]:
store.put('obj2', frame, format='table')
store.select('obj2', where=['index >= 10 and index <= 15'])

           a
10  0.257041
11 -0.839369
12  1.128723
13  1.281893
14 -0.830483
15  0.244220

In [98]:
store.close()

In [99]:
frame.to_hdf('mydata.h5', 'obj3', format='table')
pd.read_hdf('mydata.h5', 'obj3', where=['index >= 10 and index <= 15'])

           a
10  0.257041
11 -0.839369
12  1.128723
13  1.281893
14 -0.830483
15  0.244220

In [101]:
pip install xlrd

Collecting xlrd
  Downloading https://files.pythonhosted.org/packages/b0/16/63576a1a001752e34bf8ea62e367997530dc553b689356b9879339cf45a4/xlrd-1.2.0-py2.py3-none-any.whl (103kB)
     |████████████████████████████████| 112kB 410kB/s eta 0:00:01
Installing collected packages: xlrd
Successfully installed xlrd-1.2.0
Note: you may need to restart the kernel to use updated packages.

In [102]:
xlsx = pd.ExcelFile('ex1.xlsx')

In [107]:
pd.read_excel(xlsx, 'Sheet1')

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [109]:
pip install openpyxl

Collecting openpyxl
  Downloading https://files.pythonhosted.org/packages/6f/af/88ff9eef0b8f665aee1111ac6cede5ad12190c5bd726242bd2b26fc21b32/openpyxl-3.0.0.tar.gz (172kB)
     |████████████████████████████████| 174kB 405kB/s eta 0:00:01
Collecting jdcal
  Downloading https://files.pythonhosted.org/packages/f0/da/572cbc0bc582390480bbd7c4e93d14dc46079778ed915b505dc494b37c57/jdcal-1.4.1-py2.py3-none-any.whl
Collecting et_xmlfile
  Downloading https://files.pythonhosted.org/packages/22/28/a99c42aea746e18382ad9fb36f64c1c1f04216f41797f2f0fa567da11388/et_xmlfile-1.0.1.tar.gz
Building wheels for collected packages: openpyxl, et-xmlfile
  Building wheel for openpyxl (setup.py) ... done
  Created wheel for openpyxl: filename=openpyxl-3.0.0-py2.py3-none-any.whl size=241187 sha256=f03859f8d0af289ad8ff52d3606834ff1413a3a12ba479e7c37a6984969b9f5e
  Stored in directory: /Users/jo-eun-yeob/Library/Caches/pip/wheels/34/ee/6c/1279f7b70ea72432c2cef15dd3d915477cb3771d1618f6b8ef
  Building wheel for et-xmlfile (setup.py) ... done
  Created wheel for et-xmlfile: filename=et_xmlfile-1.0.1-cp37-none-any.whl size=8917 sha256=0091219be33bb0363c2cb71ba905a74f56501b68f967ab49facd9bff5487a6f0
  Stored in directory: /Users/jo-eun-yeob/Library/Caches/pip/wheels/2a/77/35/0da0965a057698121fc7d8c5a7a9955cdbfb3cc4e2423cad39
Successfully built openpyxl et-xmlfile
Installing collected packages: jdcal, et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.0.1 jdcal-1.4.1 openpyxl-3.0.0
Note: you may need to restart the kernel to use updated packages.

In [111]:
writer = pd.ExcelWriter('ex2.xlsx')
frame.to_excel(writer, 'Sheet1')
writer.save()

In [112]:
frame.to_excel('ex2.xlsx')

In [114]:
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

In [119]:
data = resp.json()
data

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/29154',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/29154/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/29154/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/29154/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/29154',
  'id': 510620845,
  'node_id': 'MDU6SXNzdWU1MTA2MjA4NDU=',
  'number': 29154,
  'title': "BLD: ModuleNotFoundError: No module named 'sphinx' during dev setup",
  'user': {'login': 'jgehrcke',
   'id': 265630,
   'node_id': 'MDQ6VXNlcjI2NTYzMA==',
   'avatar_url': 'https://avatars0.githubusercontent.com/u/265630?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jgehrcke',
   'html_url': 'https://github.com/jgehrcke',
   'followers_url': 'https://api.github.com/users/jgehrcke/followers',
   'following_url': 'https://api.github.com/users/jgehrcke/following{/other_user}',
   'gists_url': 'https://api.github.com/users/jgehrcke/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/jgehrcke/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/jgehrcke/subscriptions',
   'organizations_url': 'https://api.github.com/users/jgehrcke/orgs',
   'repos_url': 'https://api.github.com/users/jgehrcke/repos',
   'events_url': 'https://api.github.com/users/jgehrcke/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/jgehrcke/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2019-10-22T12:25:13Z',
  'updated_at': '2019-10-22T12:27:10Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'body': 'Following https://dev.pandas.io/docs/development/contributing.html#creating-a-python-environment-pip I ran into:\r\n\r\n```\r\n$ python -m pip install -r requirements-dev.txt\r\nCollecting git+https://github.com/pandas-dev/pandas-sphinx-theme.git@master (from -r requirements-dev.txt (line 68))\r\n  Cloning https://github.com/pandas-dev/pandas-sphinx-theme.git (to revision master) to /tmp/pip-req-build-zo7xt1n7\r\n    Complete output from command python setup.py egg_info:\r\n    Traceback (most recent call last):\r\n      File "<string>", line 1, in <module>\r\n      File "/tmp/pip-req-build-zo7xt1n7/setup.py", line 4, in <module>\r\n        from pandas_sphinx_theme import __version__\r\n      File "/tmp/pip-req-build-zo7xt1n7/pandas_sphinx_theme/__init__.py", line 8, in <module>\r\n        import sphinx.builders.html\r\n    ModuleNotFoundError: No module named \'sphinx\'\r\n```\r\n\r\nThat is, setting up `requirements-dev.txt` already requires `sphinx`. One ignorant but simple solution would be to do a `python -m pip install sphinx` prior to doing `python -m pip install -r requirements-dev.txt`. WDYT?'},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/29153',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/29153/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/29153/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/29153/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/29153',
  'id': 510617876,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0MzMwOTYwNTkx',
  'number': 29153,
  'title': 'Remove TestData from series-tests test_api.py',
  'user': {'login': 'SaturnFromTitan',
   'id': 17853006,
   'node_id': 'MDQ6VXNlcjE3ODUzMDA2',
   'avatar_url': 'https://avatars0.githubusercontent.com/u/17853006?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/SaturnFromTitan',
   'html_url': 'https://github.com/SaturnFromTitan',
   'followers_url': 'https://api.github.com/users/SaturnFromTitan/followers',
   'following_url': 'https://api.github.com/users/SaturnFromTitan/following{/other_user}',
   'gists_url': 'https://api.github.com/users/SaturnFromTitan/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/SaturnFromTitan/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/SaturnFromTitan/subscriptions',
   'organizations_url': 'https://api.github.com/users/SaturnFromTitan/orgs',
   'repos_url': 'https://api.github.com/users/SaturnFromTitan/repos',
   'events_url': 'https://api.github.com/users/SaturnFromTitan/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/SaturnFromTitan/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 127685,
    'node_id': 'MDU6TGFiZWwxMjc2ODU=',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Testing',
    'name': 'Testing',
    'color': 'C4A000',
    'default': False}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': {'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/16',
   'html_url': 'https://github.com/pandas-dev/pandas/milestone/16',
   'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/16/labels',
   'id': 174211,
   'node_id': 'MDk6TWlsZXN0b25lMTc0MjEx',
   'number': 16,
   'title': '1.0',
   'description': '',
   'creator': {'login': 'wesm',
    'id': 329591,
    'node_id': 'MDQ6VXNlcjMyOTU5MQ==',
    'avatar_url': 'https://avatars2.githubusercontent.com/u/329591?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/wesm',
    'html_url': 'https://github.com/wesm',
    'followers_url': 'https://api.github.com/users/wesm/followers',
    'following_url': 'https://api.github.com/users/wesm/following{/other_user}',
    'gists_url': 'https://api.github.com/users/wesm/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/wesm/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/wesm/subscriptions',
    'organizations_url': 'https://api.github.com/users/wesm/orgs',
    'repos_url': 'https://api.github.com/users/wesm/repos',
    'events_url': 'https://api.github.com/users/wesm/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/wesm/received_events',
    'type': 'User',
    'site_admin': False},
   'open_issues': 141,
   'closed_issues': 682,
   'state': 'open',
   'created_at': '2012-09-13T02:13:00Z',
   'updated_at': '2019-10-22T12:43:47Z',
   'due_on': '2019-11-01T07:00:00Z',
   'closed_at': None},
  'comments': 0,
  'created_at': '2019-10-22T12:19:29Z',
  'updated_at': '2019-10-22T12:43:10Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/29153',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/29153',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/29153.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/29153.patch'},
  'body': 'Part of #22550\r\n\r\n* Replaced TestData usage in `pandas/tests/series/test_api.py` with fixtures\r\n\r\n- [x] tests added / passed\r\n- [x] passes `black pandas`\r\n- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`\r\n'},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/29152',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/29152/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/29152/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/29152/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/29152',
  'id': 510617565,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0MzMwOTYwMzMz',
  'number': 29152,
  'title': 'DOC: attempt to fix contributors for 0.24.0',
  'user': {'login': 'jgehrcke',
   'id': 265630,
   'node_id': 'MDQ6VXNlcjI2NTYzMA==',
   'avatar_url': 'https://avatars0.githubusercontent.com/u/265630?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jgehrcke',
   'html_url': 'https://github.com/jgehrcke',
   'followers_url': 'https://api.github.com/users/jgehrcke/followers',
   'following_url': 'https://api.github.com/users/jgehrcke/following{/other_user}',
   'gists_url': 'https://api.github.com/users/jgehrcke/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/jgehrcke/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/jgehrcke/subscriptions',
   'organizations_url': 'https://api.github.com/users/jgehrcke/orgs',
   'repos_url': 'https://api.github.com/users/jgehrcke/repos',
   'events_url': 'https://api.github.com/users/jgehrcke/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/jgehrcke/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 134699,
    'node_id': 'MDU6TGFiZWwxMzQ2OTk=',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs',
    'name': 'Docs',
    'color': '3465A4',
    'default': False}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': {'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/16',
   'html_url': 'https://github.com/pandas-dev/pandas/milestone/16',
   'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/16/labels',
   'id': 174211,
   'node_id': 'MDk6TWlsZXN0b25lMTc0MjEx',
   'number': 16,
   'title': '1.0',
   'description': '',
   'creator': {'login': 'wesm',
    'id': 329591,
    'node_id': 'MDQ6VXNlcjMyOTU5MQ==',
    'avatar_url': 'https://avatars2.githubusercontent.com/u/329591?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/wesm',
    'html_url': 'https://github.com/wesm',
    'followers_url': 'https://api.github.com/users/wesm/followers',
    'following_url': 'https://api.github.com/users/wesm/following{/other_user}',
    'gists_url': 'https://api.github.com/users/wesm/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/wesm/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/wesm/subscriptions',
    'organizations_url': 'https://api.github.com/users/wesm/orgs',
    'repos_url': 'https://api.github.com/users/wesm/repos',
    'events_url': 'https://api.github.com/users/wesm/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/wesm/received_events',
    'type': 'User',
    'site_admin': False},
   'open_issues': 141,
   'closed_issues': 682,
   'state': 'open',
   'created_at': '2012-09-13T02:13:00Z',
   'updated_at': '2019-10-22T12:43:47Z',
   'due_on': '2019-11-01T07:00:00Z',
   'closed_at': None},
  'comments': 2,
  'created_at': '2019-10-22T12:18:54Z',
  'updated_at': '2019-10-22T12:48:19Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/29152',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/29152',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/29152.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/29152.patch'},
  'body': 'This hopefully addresses https://github.com/pandas-dev/pandas/issues/29151, please review!\r\n\r\nCC @TomAugspurger @jreback '},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/29151',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/29151/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/29151/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/29151/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/29151',
  'id': 510613924,
  'node_id': 'MDU6SXNzdWU1MTA2MTM5MjQ=',
  'number': 29151,
  'title': 'DOC: contributors section for v0.24.0 shows too many contributors',
  'user': {'login': 'jgehrcke',
   'id': 265630,
   'node_id': 'MDQ6VXNlcjI2NTYzMA==',
   'avatar_url': 'https://avatars0.githubusercontent.com/u/265630?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jgehrcke',
   'html_url': 'https://github.com/jgehrcke',
   'followers_url': 'https://api.github.com/users/jgehrcke/followers',
   'following_url': 'https://api.github.com/users/jgehrcke/following{/other_user}',
   'gists_url': 'https://api.github.com/users/jgehrcke/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/jgehrcke/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/jgehrcke/subscriptions',
   'organizations_url': 'https://api.github.com/users/jgehrcke/orgs',
   'repos_url': 'https://api.github.com/users/jgehrcke/repos',
   'events_url': 'https://api.github.com/users/jgehrcke/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/jgehrcke/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 134699,
    'node_id': 'MDU6TGFiZWwxMzQ2OTk=',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs',
    'name': 'Docs',
    'color': '3465A4',
    'default': False}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': {'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/16',
   'html_url': 'https://github.com/pandas-dev/pandas/milestone/16',
   'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/16/labels',
   'id': 174211,
   'node_id': 'MDk6TWlsZXN0b25lMTc0MjEx',
   'number': 16,
   'title': '1.0',
   'description': '',
   'creator': {'login': 'wesm',
    'id': 329591,
    'node_id': 'MDQ6VXNlcjMyOTU5MQ==',
    'avatar_url': 'https://avatars2.githubusercontent.com/u/329591?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/wesm',
    'html_url': 'https://github.com/wesm',
    'followers_url': 'https://api.github.com/users/wesm/followers',
    'following_url': 'https://api.github.com/users/wesm/following{/other_user}',
    'gists_url': 'https://api.github.com/users/wesm/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/wesm/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/wesm/subscriptions',
    'organizations_url': 'https://api.github.com/users/wesm/orgs',
    'repos_url': 'https://api.github.com/users/wesm/repos',
    'events_url': 'https://api.github.com/users/wesm/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/wesm/received_events',
    'type': 'User',
    'site_admin': False},
   'open_issues': 141,
   'closed_issues': 682,
   'state': 'open',
   'created_at': '2012-09-13T02:13:00Z',
   'updated_at': '2019-10-22T12:43:47Z',
   'due_on': '2019-11-01T07:00:00Z',
   'closed_at': None},
  'comments': 0,
  'created_at': '2019-10-22T12:12:17Z',
  'updated_at': '2019-10-22T12:43:39Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'body': "Found my name in https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.24.0.html#contributors. Did not contribute to that release. Contributed to 0.25.0 (that section is empty, though, see https://github.com/pandas-dev/pandas/issues/27687).\r\n\r\nIn the `doc/source/whatsnew/v0.24.0.rst` the culprit seems to be `contributors:: v0.23.4..HEAD`, let's change `HEAD` to `v0.24.0`?"},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/29150',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/29150/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/29150/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/29150/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/29150',
  'id': 510613840,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0MzMwOTU3MTk3',
  'number': 29150,
  'title': 'Remove TestData from series-tests test_timeseries.py',
  'user': {'login': 'SaturnFromTitan',
   'id': 17853006,
   'node_id': 'MDQ6VXNlcjE3ODUzMDA2',
   'avatar_url': 'https://avatars0.githubusercontent.com/u/17853006?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/SaturnFromTitan',
   'html_url': 'https://github.com/SaturnFromTitan',
   'followers_url': 'https://api.github.com/users/SaturnFromTitan/followers',
   'following_url': 'https://api.github.com/users/SaturnFromTitan/following{/other_user}',
   'gists_url': 'https://api.github.com/users/SaturnFromTitan/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/SaturnFromTitan/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/SaturnFromTitan/subscriptions',
   'organizations_url': 'https://api.github.com/users/SaturnFromTitan/orgs',
   'repos_url': 'https://api.github.com/users/SaturnFromTitan/repos',
   'events_url': 'https://api.github.com/users/SaturnFromTitan/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/SaturnFromTitan/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 127685,
    'node_id': 'MDU6TGFiZWwxMjc2ODU=',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Testing',
    'name': 'Testing',
    'color': 'C4A000',
    'default': False}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': {'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/16',
   'html_url': 'https://github.com/pandas-dev/pandas/milestone/16',
   'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/16/labels',
   'id': 174211,
   'node_id': 'MDk6TWlsZXN0b25lMTc0MjEx',
   'number': 16,
   'title': '1.0',
   'description': '',
   'creator': {'login': 'wesm',
    'id': 329591,
    'node_id': 'MDQ6VXNlcjMyOTU5MQ==',
    'avatar_url': 'https://avatars2.githubusercontent.com/u/329591?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/wesm',
    'html_url': 'https://github.com/wesm',
    'followers_url': 'https://api.github.com/users/wesm/followers',
    'following_url': 'https://api.github.com/users/wesm/following{/other_user}',
    'gists_url': 'https://api.github.com/users/wesm/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/wesm/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/wesm/subscriptions',
    'organizations_url': 'https://api.github.com/users/wesm/orgs',
    'repos_url': 'https://api.github.com/users/wesm/repos',
    'events_url': 'https://api.github.com/users/wesm/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/wesm/received_events',
    'type': 'User',
    'site_admin': False},
   'open_issues': 141,
   'closed_issues': 682,
   'state': 'open',
   'created_at': '2012-09-13T02:13:00Z',
   'updated_at': '2019-10-22T12:43:47Z',
   'due_on': '2019-11-01T07:00:00Z',
   'closed_at': None},
  'comments': 0,
  'created_at': '2019-10-22T12:12:11Z',
  'updated_at': '2019-10-22T12:42:58Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/29150',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/29150',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/29150.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/29150.patch'},
  'body': 'Part of #22550\r\n\r\n* Replaced TestData usage in `pandas/tests/series/test_timeseries.py` with fixtures\r\n\r\n- [x] tests added / passed\r\n- [x] passes `black pandas`\r\n- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`\r\n'},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/29149',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/29149/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/29149/comments',

In [120]:
data = resp.json()
data[0]['title']

"BLD: ModuleNotFoundError: No module named 'sphinx' during dev setup"

In [121]:
issues = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])

In [122]:
issues

,number,title,labels,state
0,29154,BLD: ModuleNotFoundError: No module named 'sph...,[],open
1,29153,Remove TestData from series-tests test_api.py,"[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...",open
2,29152,DOC: attempt to fix contributors for 0.24.0,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",open
3,29151,DOC: contributors section for v0.24.0 shows to...,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",open
4,29150,Remove TestData from series-tests test_timeser...,"[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...",open
5,29149,Remove TestData from series-tests test_sorting.py,"[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...",open
6,29148,Remove TestData from series-tests test_repr.py,"[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...",open
7,29146,df.interpolate(method='pad') axis is not cons...,[],open
8,29145,set_axis with callable,[],open
9,29144,BUG/TST: ensure groupby.agg preserves extensio...,"[{'id': 849023693, 'node_id': 'MDU6TGFiZWw4NDk...",open
...,...,...,...,...
20,29132,NDFrame.interpolate(): variable 'ax' not assig...,"[{'id': 2822342, 'node_id': 'MDU6TGFiZWwyODIyM...",open
21,29131,[BUG] Fixed behavior of DataFrameGroupBy.apply...,"[{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...",open
22,29130,merge_asof() returns cryptic error with bad ar...,"[{'id': 42670965, 'node_id': 'MDU6TGFiZWw0MjY3...",open
23,29129,Using groupby with nlargest drops the groupby ...,"[{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...",open
24,29128,Variance of nullable Int64 ignores ddof argument,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
25,29125,Unify error messages when opening inexistent e...,"[{'id': 2301354, 'node_id': 'MDU6TGFiZWwyMzAxM...",open
26,29124,Fixed Inconsistent GroupBy Output Shape with D...,"[{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...",open
27,29122,Make color validation more forgiving,"[{'id': 2413328, 'node_id': 'MDU6TGFiZWwyNDEzM...",open
28,29118,ENH: Add built-in function for Styler to forma...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
29,29116,ENH: Implement Keyword Aggregation for DataFra...,[],open

In [125]:
import sqlite3

query = """
CREATE TABLE test
(a VARCHAR(20), b VARCHAR(20), c REAL, d INTEAGER);
"""
con = sqlite3.connect('mydata.sqlite')
con.execute(query)
con.commit

In [126]:
data = [('Atlanta', 'Georgia', 1.25, 6),
       ('Tallahassee', 'Florida', 2.6, 3),
       ('Sacramento', 'California', 1.7, 5)
       ]
stmt = "INSERT INTO test VALUES(?,?,?,?)"
con.executemany(stmt, data)
con.commit()

In [130]:
cursor = con.execute('select * from test')
rows = cursor.fetchall()
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

In [132]:
pip install sqlalchemy

Collecting sqlalchemy
  Downloading https://files.pythonhosted.org/packages/14/0e/487f7fc1e432cec50d2678f94e4133f2b9e9356e35bacc30d73e8cb831fc/SQLAlchemy-1.3.10.tar.gz (6.0MB)
     |████████████████████████████████| 6.0MB 537kB/s eta 0:00:01
Building wheels for collected packages: sqlalchemy
  Building wheel for sqlalchemy (setup.py) ... done
  Created wheel for sqlalchemy: filename=SQLAlchemy-1.3.10-cp37-cp37m-macosx_10_14_x86_64.whl size=1154882 sha256=bb7c115f62aa3ee1edd1a321d6314a296aa80809a58a7a3232aafcd64b1ced5a
  Stored in directory: /Users/jo-eun-yeob/Library/Caches/pip/wheels/4b/b2/89/cd2231ee623987c605f049df55f40a3e4252ef6a15b94836c2
Successfully built sqlalchemy
Installing collected packages: sqlalchemy
Successfully installed sqlalchemy-1.3.10
Note: you may need to restart the kernel to use updated packages.

In [136]:
import sqlalchemy as sqla
db = sqla.create_engine('sqlite:///mydata.sqlite')
pd.read_sql('select * from test', db)

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5